In [2]:
import numpy
arry= numpy.array([1,2,3,4,5,6])
print(arry)

[1 2 3 4 5 6]


In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
#Checking NumPy Version
#The version string is stored under __version__ attribute.


import numpy as np

print(np.__version__)


1.19.2


In [ ]:
Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is
#numpy.ndarray type.

In [9]:
#0-D Arrays
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.
import numpy as np
ab= np.array(30)
print(ab)

30


In [ ]:
1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [13]:
#2-d array
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [69]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [17]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6], [3, 2, 1]], [[1, 2, 3], [4, 5, 6], [5, 4, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [5 4 6]]]


In [18]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [21]:
 import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6], [3, 2, 1]], [[1, 2, 3], [4, 5, 6], [5, 4, 6]], [[1 , 3, 2], [3, 5, 7],[2 ,5 ,6]],[[1, 2, 3], [4, 5, 6], [5, 4, 6]]])

print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [5 4 6]]

 [[1 3 2]
  [3 5 7]
  [2 5 6]]

 [[1 2 3]
  [4 5 6]
  [5 4 6]]]
3


In [ ]:
Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1

In [24]:
import numpy as np
a=np.array([1,2,3,4,7,8,9])
print(a)
print(a[2]+a[4])

[1 2 3 4 7 8 9]
10


In [25]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [35]:
#Negative Indexing
#Use negative indexing to access an array from the end.

import numpy as np

arr = np.array([[3,1,2,3,4,5], [2,6,7,8,9,12]])

print('Last element from 2nd dim: ', arr[0, -1])

Last element from 2nd dim:  5


In [19]:

import numpy as np

arr = np.array([[3,1,2,3,4,5], [2,6,7,8,9,12]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  12


In [21]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [22]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [23]:
arr[1,0]

array([7, 8, 9])

In [ ]:
Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
#The result includes the start index, but excludes the end index.

[2 3 4 5]


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:5])

[1 2 3 4 5]


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-1:-1])
print(arr[-2:-1])
print(arr[-3:-1])
print(arr[-4:-1])


print(arr[-3:-2])
print(arr[-4:-2])

[]
[6]
[5 6]
[4 5 6]
[5]
[4 5]


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [50]:
print(arr[1::2])
print(arr[:5:2])
print(arr[1:5:2])
print(arr[1:6:2])
print(arr[1:7:3])

[2 4 6]
[1 3 5]
[2 4]
[2 4 6]
[2 5]


In [59]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1])
print(arr[0:2, 2])
print(arr[0:2, 3])
print(arr[0:1, 3])

[2 7]
[3 8]
[4 9]
[4]


In [ ]:
#Note: Remember that second element has index 1.

In [60]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [66]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2: 5])

[[ 3  4  5]
 [ 8  9 10]]


In [ ]:
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [ ]:
Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [74]:
import numpy as np
a= np.array([1,2,3,4], dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [75]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [76]:
import numpy as np
a=np.array([1,2,3,4,5,6])
x=a.copy()
a[1]=21
print(x)
print(a)

[1 2 3 4 5 6]
[ 1 21  3  4  5  6]


In [77]:
import numpy as np
b=np.array([1,2,3,4,5,6])
c=a.view()
b[1]=21
print(c)
print(b)

[ 1 21  3  4  5  6]
[ 1 21  3  4  5  6]


In [ ]:
Check if Array Owns it's Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [78]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [79]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)
#The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

(2, 4)


In [80]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.shape)

(5,)


In [83]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] , [[7, 8, 9], [10, 11, 12]]])

print(arr.shape)

(3, 2, 3)


In [84]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
Reshaping arrays
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [85]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [86]:
#Convert the following 1-D array with 12 elements into a 3-D array.

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [89]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13,14,15,16,17,18])

newarr = arr.reshape(2, 3, 3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [92]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [96]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [94]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


In [98]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
for x in a:
#    for y in x:
        print(x)

[1 2 3]
[4 5 6]


In [100]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [101]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [ ]:
Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [102]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [107]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [109]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [106]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
Splitting NumPy Arrays
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [6]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

harr=np.vsplit(arr, 3)
print(harr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [23]:
import numpy as np

arr = np.array([8, 2, 2, 4, 9, 6, 7, 8])

x = np.where(arr%2 == 1)

y= np.where(arr%2==0)

print(x)
print(y)

(array([4, 6], dtype=int64),)
(array([0, 1, 2, 3, 5, 7], dtype=int64),)


In [26]:
import numpy as np

arr = np.array([6, 7, 8, 9])

y = np.searchsorted(arr, 7)

x = np.searchsorted(arr, 7, side="right")

print(y)

print(x)


1
2


In [27]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [ ]:
Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [28]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [33]:
import numpy as np

arr = np.array([41, 42, 43, 42])

x = [True, False, True, False+]

newarr = arr[x]

print(newarr)

[41 43]


In [34]:
import numpy as np

arr= np.array([15,12,16,11,12,14,18])

filter_a=[]

for ele in arr:
    
    if ele > 15:
        filter_a.append(True)
    else:
        filter_a.append(False)
        
print(arr)
print(filter_a)
print(arr[filter_a])


[15 12 16 11 12 14 18]
[False, False, True, False, False, False, True]
[16 18]


In [50]:
import numpy as np

arr = np.array([[1, 2, 3,6,7,4, 5, 6,8,9,10,11,12,13,14,15,16,17]])

newarr = arr.reshape(2,3,3)

print(newarr)

[[[ 1  2  3]
  [ 6  7  4]
  [ 5  6  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
